### ISSUE TITLE
SSE2 binary+GCC6  

### ISSUE THREAD

**Issue by nyancat18** [appleseedhq/appleseed#1208]
some very popular distros uses GCC6  

could you add support to that?

**Comment by dictoon** [comment]
By "support", what do you mean? I would think we already support gcc 6 out of the box. We just don't provide any pre-made gcc 6 builds.

**Comment by est77** [comment]
We currently test gcc 4.6, 4.8 and 5, in C++03 and C++11 mode (if supported by the gcc version).
I'm not sure if appleseed builds with gcc 6, but if it does not, it should be easy to fix.

Our release is built with gcc 4.8 because that's the "official" compiler for VFX projects.
It's the version specified in the VFX platform and the one you need to integrate your software into 
DCC apps like Autodesk Maya.

Is there any reason you cannot use the prebuilt release?

**Comment by triceratops1** [comment]
SSE2   support  @est77  could you give a SSE2 build? 

if you make it can  package it (normal+binary) for arch/

**Comment by est77** [comment]
I don't have gcc 6. My linux distribution has 5.3.
What I could do is a gcc 4.8 build with SSE2 (current release is gcc 4.8 with SSE4.2).
Would that be useful?

**Comment by triceratops1** [comment]
second option 
What I could do is a gcc 4.8 build with SSE2 (current release is gcc 4.8 with SSE4.2).


if i've an issue i gonna comment you :D

**Comment by est77** [comment]
Ok. I'll make one. It will take a bit of time, I need to rebuild some deps with SSE2.
Just out of curiosity, is the SSE2 restriction an arch/ thing?

**Comment by triceratops1** [comment]
@est77  arch doesnt have issues with sse2  


its ancient hardware the issue :)

**Comment by dictoon** [comment]
FYI Travis now builds appleseed with gcc 6.
