### ISSUE TITLE
Skip shadow rays for low contribution lights

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#1228]

**Comment by est77** [comment]
In Arnold this is called low light thereshold. It skips illumination (and tracing a shadow rays) if the contribution of a light is bellow the thereshold.

**Comment by aytekaman** [comment]
I will try to handle this.

**Comment by dictoon** [comment]
Before we can close this issue, there is one important improvement that we should consider:  When a light contribution is low, use Russian Roulette to skip it without introducing bias.

**Comment by aytekaman** [comment]
I will send a PR soon (hopefully today or maybe tomorrow).

**Comment by aytekaman** [comment]
Here is the PR: #1423
-There is a slight performance penalty due to the overhead of RR computation. However, scenes with low light threshold are still rendered much faster (especially when light sample count is high).
-Now, average luminosity values seem almost equal for images rendered with different low light threshold values. This was not the case before.

**Comment by dictoon** [comment]
Awesome! I'll review now.

**Comment by dictoon** [comment]
Note that if you let images converge long enough to be mostly noise-free, the overall brightness should be *identical* with and without a low light threshold.
