### ISSUE TITLE
Update attribute editor when clearing crop window

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#1258]
When the attribute editor is showing the attributes of a frame, clearing the crop window with the toolbar button should also clear the crop window in the attribute editor.

**Comment by Narann** [comment]
Not always. I guess you should have added: "Only when a relevant entity (beauty, render pass, I don't remember the name) is selected".

**Comment by dictoon** [comment]
Updated the description, I think it's pretty accurate now.

**Comment by aiivashchenko** [comment]
I'll take this one to fix, if you don't mind

**Comment by aiivashchenko** [comment]
I've found another related bug, I guess. If the "Crop window" attribute will be updated through "Project" > "Output" > "beauty" > right click > "Edit" dedicated dialog window while "beauty" attribute editor is active it will also take no effect to field into attribute editor.

**Comment by aiivashchenko** [comment]
Hello, @dictoon! I've achieved some results on that task, however I am not quite sure that this solution is the one you've been expecting, since there are a lot of other ways to reach the goal.

For example, we can
1. directly connect signals in MainWindow
2. emit signal in ClearRenderRegionAction
3. connect signal directly to QLineEdit clear() slot on its creation
4. pass the call down through hierarchy without signals
etc. 

All the points are having some pros and cons, so if you'll have some recommendations please let me know and I'll improve the proposed solution. Here is a [PR](https://github.com/appleseedhq/appleseed/pull/1291).

**Comment by dictoon** [comment]
Done.
