### ISSUE TITLE
Integration with LeoCAD (render LDraw models and annimations)

### ISSUE THREAD

**Issue by Symbian9** [appleseedhq/appleseed#1662]
> LeoCAD is a CAD program for creating virtual LEGO models.

Issue on LeoCAD tracker
* https://github.com/leozide/leocad/issues/70

**Comment by dictoon** [comment]
@Symbian9 That sounds very interesting and we will be glad to assist you in adding support for appleseed in LeoCAD! Let us know if/when you start working on this, we will gladly invite you on the appleseed Slack team if you want to get real time answers to your questions.

Closing this issue since the work should be entirely on LeoCAD's side (modulo bugs and missing features in appleseed which will mandate separate issues).
