### ISSUE TITLE
User related permissive problems on Linux? "error while loading shared libraries" 

### ISSUE THREAD

**Issue by leonard7e** [appleseedhq/appleseed#1738]
Hi.

If I try to install appleseed into /opt/appleseed and do 

`leonard@LittlePony» sudo chown -R root:root appleseed/
`
Appleseed binaries stop working. Giving error message

```
leonard@LittlePony» /opt/appleseed/bin/appleseed.cli 
/opt/appleseed/bin/appleseed.cli: error while loading shared libraries: libboost_atomic-gcc48-mt-1_61.so.1.61.0: cannot open shared object file: No such file or directory

```

If I do

`leonard@LittlePony» sudo chown -R leonard:leonard /opt/appleseed/`

Appleseed works again.

**Comment by dictoon** [comment]
Thanks @leonard7e, we're looking into it.

**Comment by est77** [comment]
Hi
I never tried running appleseed as root, but we had other reports suggesting that RPATHs (what we use to locate shared libraries in appleseed) do not work when executables are owned by root, likely because of security reasons.

We don't recommend running appleseed as root anyway. If for some reason you need to do it, you can use ld.conf or LD_LIBRARY_PATH.

**Comment by leonard7e** [comment]
Hi.
I never intendet to run appleseed with root privileges. oO
It was about placing appleseed where many user could access, rather then giving a local copy to each user. 
But thank you for your answer.
