### ISSUE TITLE
Light Tree crashes with light-emitting OSL shaders

### ISSUE THREAD

**Issue by luisbarrancos** [appleseedhq/appleseed#1818]
Changing the *Light Sampler* from *CDF* to *Light Tree* mode crashes the attached scene (renamed to end with .zip extension since github does not recognizes appleseedz)

[change_to_lighttree_crash.appleseedz.zip](https://github.com/appleseedhq/appleseed/files/1670852/change_to_lighttree_crash.appleseedz.zip)

**Comment by dictoon** [comment]
I can repro after changing light sampling mode from CDF to Light Tree and hitting render.

I suspect it's due to the light tree code not handling light emitting OSL shaders.

The code derefeences a null pointer here:
https://github.com/appleseedhq/appleseed/blob/efdb6537738e8669118e56683dce0f3096bad051/src/appleseed/renderer/kernel/lighting/lighttree.cpp#L210

`triangle.m_material` is `asBlackbody1SG_material` but `edf` is `nullptr`.

**Comment by dictoon** [comment]
I confirm the above suspicion. The cause of the problem is that `OSLMaterial::has_emission()` correctly identifies that `asBlackbody1SG_material` emits light but the light tree code does not handle light-emitting OSL shaders.

**Comment by dictoon** [comment]
Fixed.
