### ISSUE TITLE
Fix as_texture shader for single-channel textures

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#1903]
[This commit](https://github.com/appleseedhq/appleseed/commit/595ee52ff25a85b7579516c5c0166c134e5bcce7) introduced a bug: when the texture has a single channel, `out_color` is left to its default value of (1, 1, 1). It should probably be set based on the value of that single channel, e.g.

    out_color = color(out_channel);

We should probably also set `out_channel` in the case of multi-channel textures.

**Comment by luisbarrancos** [comment]
@dictoon what are we going to set the single channel output to in the case of multiple channels? The first channel (R) ? Alpha if present? Luminance of RGB?

**Comment by dictoon** [comment]
@luisbarrancos I'd say luminance ("black & white output") would be more intuitive.

**Comment by luisbarrancos** [comment]
@dictoon ok, have in mind the coefficients are provided by Y in the XYZ->RGB matrix, so they are color space dependent. We can hardcode to Rec.709 luminance for now.

**Comment by dictoon** [comment]
That's plenty enough. We just need to do something reasonable.

**Comment by luisbarrancos** [comment]
on 2nd thoughts, if CMS is active, we have information to use the proper Y coefficients and *do the right thing*. No need to compromise. If CMS is inactive though, then data is assumed raw, and getting the relative luminance would be meaningless since it's RGBW relative, so the average of RGB is used in this case. The docs will be updated to reflect this as well.
