### ISSUE TITLE
InvertColor tweaks, minor issues

### ISSUE THREAD

**Issue by luisbarrancos** [appleseedhq/appleseed#2367]
@Mango-3 i missed the review, but there are a couple of points worth reviewing in https://github.com/appleseedhq/appleseed/blob/master/src/appleseed.shaders/src/appleseed/as_inv_color.osl

In https://github.com/appleseedhq/appleseed/blob/master/src/appleseed.shaders/src/appleseed/as_inv_color.osl#L32can you please rename it to *as_invert_color* ? For consistency's sake with the other nodes.

In https://github.com/appleseedhq/appleseed/blob/master/src/appleseed.shaders/src/appleseed/as_inv_color.osl#L62 please rename the color models *rgb*, *hsv*, *hls* to *RGB*, *HSV*, *HLS*.

In https://github.com/appleseedhq/appleseed/blob/master/src/appleseed.shaders/src/appleseed/as_inv_color.osl#L62 , CIE XYZ and xyY require knowledge of RGB primaries and white point. You need to connect this with the color management information passed by the plugin and/or explicitly add parameters for the user to choose the input color primaries and white point, **and** the working/rendering space input color primaries and white point.
It's not very intuitive from a user POV to invert CIE *x* or *y* coordinates - what does it mean from a user POV? Inverting Y would invert the relative luminance though.
The easiest solution would be to keep it simple and remove the *CIE XYZ* and *CIE xyY* options there since *RGB*, *HSV*, *HLS* would cover almost the totality of use cases.

In https://github.com/appleseedhq/appleseed/blob/master/src/appleseed.shaders/src/appleseed/as_inv_color.osl#L71 (and line 82 and 93)
The widget *checkBox* is either *on* or *off*: having the integer *min* and *max* values there is redundant.

In https://github.com/appleseedhq/appleseed/blob/master/src/appleseed.shaders/src/appleseed/as_inv_color.osl#L112 this would only work if the input colors are in [0,1] range.
If one wants to deal with HDR input we would need to convert the input into some sort of log representation to compress the range, perform the inversion, and expand again. I'm not sure this is desirable or useful here so take it with a grain of salt. The best solution would be to perhaps just clamp the input color to [0,1] then do the the inversion.

**Comment by Mango-3** [comment]
Thanks Luis, great points you have raised. 
I have some comments to add.

- I renamed the shader as suggested
- The color model names are on purpose not capitalized because this is the exact form the OSL built-in color conversion function `transformc()` expects them. The name strings get passed to it as function arguments via the popup widget. I tried the mapper widget to map RGB -> rgb etc. but it does not work with string-string key value pairs.  
- I removed CIE XYZ and xyY. Now it is same as with PxrInvert
- For Blender integer limits make sense. Blender implements the checkBox widget via adjustable slider type controls where one could easily end up like this: 
![asinvert_blender](https://user-images.githubusercontent.com/22252558/50381682-e85fd880-0695-11e9-8813-fb221288134f.PNG)
with negative values causing confusion among users.
- Added input color clamping

**Comment by luisbarrancos** [comment]
Thanks Herbert. Regarding the transformc color space, you can use a options & mapper widget with the numerical value (enum) and map the numeric value to the desired string. We do that with the subsurface shader for example, https://github.com/appleseedhq/appleseed/blob/673276031a611be02c0f70a9117f2d3337a0e95c/src/appleseed.shaders/src/appleseed/as_subsurface.osl#L52

Regarding the checkBox widget, that is strange, because OSL considered the possibility of integer sliders, float sliders, besides checkBox (and has *slidermin* and *slidermax* tokens too). I can see the problem there. Is this a Blender limitation or Blenderseed limitation? Are all shaders with *checkBox* widget affected like that?

**Comment by Mango-3** [comment]
- Ok, I changed the string mapping to have RGB, HSV & HSL in the menu selector.
- The checkBox in Blender is implemented this way. If you click on the small arrows left & right of the selector you can decrease/increase the value (which is a integer). If thereare no limits you can just click up and down the full integer range. I keep the limits [0,1] in the OSL file so one can just select 0 or 1. The real issue is that OSL has no dedicated bool type and we just use the integer for a boolean comparison and don't need the integer range of values.
It is no problem to keep the limits and has no effect on the working logic, just helps to avoid confusion for Blender users.

**Comment by luisbarrancos** [comment]
Addressed in https://github.com/appleseedhq/appleseed/pull/2369
