### ISSUE TITLE
Print final render time estimations

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed#2438]
From user Dark_z on Discord:

> It would be useful if, in the renderer's info, the renderer made an attempt to estimate the time it could take to render the whole frame based on the rolling average time it's already taken to render the current tiles. This will definitely be a rough estimation for sure, but getting an idea of how long a frame will take to render without rendering out the entire frame first is something that would be very beneficial.

**Comment by achalpandeyy** [comment]
Is anybody working on this? I'd like to try it.

**Comment by dictoon** [comment]
Go ahead.

**Comment by achalpandeyy** [comment]
How often should the renderer print estimated render time in the logs?

**Comment by dictoon** [comment]
That's a good question. Maybe every time there's a progress update? What do you think?

**Comment by achalpandeyy** [comment]
What exactly do you mean by a progress update?

How about every time we finish rendering a tile?

**Comment by achalpandeyy** [comment]
One way of approaching this issue-

1. add a member variable to `tilecallbackbase.h` to keep track of how much time it takes for a tile to get rendered

2. start the timer in `on_tile_begin()` and end it on `on_tile_end()` callback functions and store the time elapsed in the member variable

3. take the average of this member variable for all the already rendered tiles in the frame

4. since all the tiles are being rendered in parallel, we can return this average as the estimated time

what do you think?

**Comment by dictoon** [comment]
Done.
