### ISSUE TITLE
Add an alpha channel to the DepthAOV

### ISSUE THREAD

**Issue by est77** [appleseedhq/appleseed#2440]
When we don't hit an object, we output numeric_limits<float>::max(). Some applications don't like that.
We could add an alpha channel to the depth image and set it to 1 when hitting an object, 0 otherwise.
This would allow us to use depth = 0, alpha = 0 when we don't hit any object.

**Comment by achalpandeyy** [comment]
Is anybody working on this? I think I have an idea about how to approach this issue.

**Comment by dictoon** [comment]
Nobody is, you can go ahead.

**Comment by achalpandeyy** [comment]
I'm a bit confused as to how the alpha value will be useful.

I could just add an alpha channel to the `DepthAOV` class, and use it to set the depth to 0 inside the `DepthAOVAccumulator`'s implementation of `write()` function, but how would it create a difference?
We can just pass 0 instead of `numeric_limits<float>::max()` if we don't hit anything and that would do the same thing.

Essentially, I'm asking how the caller of the `write()` function will know the alpha value because we only output the depth and not the alpha?

**Comment by est77** [comment]
We need to make a difference between the case where we hit an object and the case were we don't.

**Comment by achalpandeyy** [comment]
I submitted a pull request for it #2443. Please have a look.

**Comment by dictoon** [comment]
Done in #2443.
